@startuml

entity "Recipe" as recipe {
  --
  name
}

entity "Recipe Step" as recipe_step {
  --
  order
  description
  image
}
recipe_step }o--|| "recipe" recipe

entity "Recipe Ingredient" as recipe_ingredient {
  --
  order
  quantity
  unit
}
recipe_ingredient }o--|| "step" recipe_step

entity "Ingredient" as ingredient {
  --
  name
}
ingredient "ingredient" ||--o{ recipe_ingredient

@enduml