export const enum Command {
  ENTITY_CREATE_INGREDIENT = "entity_create_ingredient",
  ENTITY_READ_INGREDIENT = "entity_read_ingredient",
  ENTITY_UPDATE_INGREDIENT = "entity_update_ingredient",
  ENTITY_DELETE_INGREDIENT = "entity_delete_ingredient",
  ENTITY_LIST_INGREDIENT = "entity_list_ingredient",
  ENTITY_COUNT_INGREDIENT = "entity_count_ingredient",

  ENTITY_CREATE_RECIPE = "entity_create_recipe",
  ENTITY_READ_RECIPE = "entity_read_recipe",
  ENTITY_UPDATE_RECIPE = "entity_update_recipe",
  ENTITY_DELETE_RECIPE = "entity_delete_recipe",
  ENTITY_LIST_RECIPE = "entity_list_recipe",
  ENTITY_COUNT_RECIPE = "entity_count_recipe",

  ENTITY_CREATE_RECIPE_FILE = "entity_create_recipe_file",
  ENTITY_READ_RECIPE_FILE = "entity_read_recipe_file",
  ENTITY_UPDATE_RECIPE_FILE = "entity_update_recipe_file",
  ENTITY_DELETE_RECIPE_FILE = "entity_delete_recipe_file",
  ENTITY_LIST_RECIPE_FILE = "entity_list_recipe_file",
  ENTITY_COUNT_RECIPE_FILE = "entity_count_recipe_file",

  ENTITY_CREATE_RECIPE_INGREDIENT = "entity_create_recipe_ingredient",
  ENTITY_READ_RECIPE_INGREDIENT = "entity_read_recipe_ingredient",
  ENTITY_UPDATE_RECIPE_INGREDIENT = "entity_update_recipe_ingredient",
  ENTITY_DELETE_RECIPE_INGREDIENT = "entity_delete_recipe_ingredient",
  ENTITY_LIST_RECIPE_INGREDIENT = "entity_list_recipe_ingredient",
  ENTITY_COUNT_RECIPE_INGREDIENT = "entity_count_recipe_ingredient",

  ENTITY_CREATE_RECIPE_STEP = "entity_create_recipe_step",
  ENTITY_READ_RECIPE_STEP = "entity_read_recipe_step",
  ENTITY_UPDATE_RECIPE_STEP = "entity_update_recipe_step",
  ENTITY_DELETE_RECIPE_STEP = "entity_delete_recipe_step",
  ENTITY_LIST_RECIPE_STEP = "entity_list_recipe_step",
  ENTITY_COUNT_RECIPE_STEP = "entity_count_recipe_step",
}
