export const enum EventQuestionChannel {
  SCRAPER_DOM_CREATE_QUESTION = "SCRAPER_DOM_CREATE_QUESTION",
  SCRAPER_DOM_CANONICAL_LINK_QUESTION = "SCRAPER_DOM_CANONICAL_LINK_QUESTION",
  SCRAPER_DOM_SELECT_QUESTION = "SCRAPER_DOM_SELECT_QUESTION",
  SCRAPER_DOM_SELECT_ALL_QUESTION = "SCRAPER_DOM_SELECT_ALL_QUESTION",
  SCRAPER_ELEMENT_TEXT_CONTENT_QUESTION = "SCRAPER_ELEMENT_TEXT_CONTENT_QUESTION",
  SCRAPER_ELEMENT_GET_ATTRIBUTE_QUESTION = "SCRAPER_ELEMENT_GET_ATTRIBUTE_QUESTION",
  SCRAPER_ELEMENT_SELECT_QUESTION = "SCRAPER_ELEMENT_SELECT_QUESTION",
  SCRAPER_ELEMENT_SELECT_ALL_QUESTION = "SCRAPER_ELEMENT_SELECT_ALL_QUESTION",
}
