export const enum EventAnswerChannel {
  SCRAPER_DOM_CREATE_ANSWER = "SCRAPER_DOM_CREATE_ANSWER",
  SCRAPER_DOM_CANONICAL_LINK_ANSWER = "SCRAPER_DOM_CANONICAL_LINK_ANSWER",
  SCRAPER_DOM_SELECT_ANSWER = "SCRAPER_DOM_SELECT_ANSWER",
  SCRAPER_DOM_SELECT_ALL_ANSWER = "SCRAPER_DOM_SELECT_ALL_ANSWER",
  SCRAPER_ELEMENT_TEXT_CONTENT_ANSWER = "SCRAPER_ELEMENT_TEXT_CONTENT_ANSWER",
  SCRAPER_ELEMENT_GET_ATTRIBUTE_ANSWER = "SCRAPER_ELEMENT_GET_ATTRIBUTE_ANSWER",
  SCRAPER_ELEMENT_SELECT_ANSWER = "SCRAPER_ELEMENT_SELECT_ANSWER",
  SCRAPER_ELEMENT_SELECT_ALL_ANSWER = "SCRAPER_ELEMENT_SELECT_ALL_ANSWER",
}
