//! This module contains all tauri event answer channels.

pub const SCRAPER_DOM_CREATE_ANSWER: &str = "SCRAPER_DOM_CREATE_ANSWER";
pub const SCRAPER_DOM_CANONICAL_LINK_ANSWER: &str = "SCRAPER_DOM_CANONICAL_LINK_ANSWER";
pub const SCRAPER_DOM_SELECT_ANSWER: &str = "SCRAPER_DOM_SELECT_ANSWER";
pub const SCRAPER_DOM_SELECT_ALL_ANSWER: &str = "SCRAPER_DOM_SELECT_ALL_ANSWER";
pub const SCRAPER_ELEMENT_TEXT_CONTENT_ANSWER: &str = "SCRAPER_ELEMENT_TEXT_CONTENT_ANSWER";
pub const SCRAPER_ELEMENT_GET_ATTRIBUTE_ANSWER: &str = "SCRAPER_ELEMENT_GET_ATTRIBUTE_ANSWER";
pub const SCRAPER_ELEMENT_SELECT_ANSWER: &str = "SCRAPER_ELEMENT_SELECT_ANSWER";
pub const SCRAPER_ELEMENT_SELECT_ALL_ANSWER: &str = "SCRAPER_ELEMENT_SELECT_ALL_ANSWER";
