pub const ENTITY_ACTION_CREATED_INGREDIENT: &str = "ENTITY_ACTION_CREATED_INGREDIENT";
pub const ENTITY_ACTION_UPDATED_INGREDIENT: &str = "ENTITY_ACTION_UPDATED_INGREDIENT";
pub const ENTITY_ACTION_DELETED_INGREDIENT: &str = "ENTITY_ACTION_DELETED_INGREDIENT";

pub const ENTITY_ACTION_CREATED_RECIPE: &str = "ENTITY_ACTION_CREATED_RECIPE";
pub const ENTITY_ACTION_UPDATED_RECIPE: &str = "ENTITY_ACTION_UPDATED_RECIPE";
pub const ENTITY_ACTION_DELETED_RECIPE: &str = "ENTITY_ACTION_DELETED_RECIPE";

pub const ENTITY_ACTION_CREATED_RECIPE_INGREDIENT: &str = "ENTITY_ACTION_CREATED_RECIPE_INGREDIENT";
pub const ENTITY_ACTION_UPDATED_RECIPE_INGREDIENT: &str = "ENTITY_ACTION_UPDATED_RECIPE_INGREDIENT";
pub const ENTITY_ACTION_DELETED_RECIPE_INGREDIENT: &str = "ENTITY_ACTION_DELETED_RECIPE_INGREDIENT";

pub const ENTITY_ACTION_CREATED_RECIPE_STEP: &str = "ENTITY_ACTION_CREATED_RECIPE_STEP";
pub const ENTITY_ACTION_UPDATED_RECIPE_STEP: &str = "ENTITY_ACTION_UPDATED_RECIPE_STEP";
pub const ENTITY_ACTION_DELETED_RECIPE_STEP: &str = "ENTITY_ACTION_DELETED_RECIPE_STEP";
