//! This module contains all tauri event question channels.

pub const SCRAPER_DOM_CREATE_QUESTION: &str = "SCRAPER_DOM_CREATE_QUESTION";
pub const SCRAPER_DOM_CANONICAL_LINK_QUESTION: &str = "SCRAPER_DOM_CANONICAL_LINK_QUESTION";
pub const SCRAPER_DOM_SELECT_QUESTION: &str = "SCRAPER_DOM_SELECT_QUESTION";
pub const SCRAPER_DOM_SELECT_ALL_QUESTION: &str = "SCRAPER_DOM_SELECT_ALL_QUESTION";
pub const SCRAPER_ELEMENT_TEXT_CONTENT_QUESTION: &str = "SCRAPER_ELEMENT_TEXT_CONTENT_QUESTION";
pub const SCRAPER_ELEMENT_INNER_TEXT_QUESTION: &str = "SCRAPER_ELEMENT_INNER_TEXT_QUESTION";
pub const SCRAPER_ELEMENT_GET_ATTRIBUTE_QUESTION: &str = "SCRAPER_ELEMENT_GET_ATTRIBUTE_QUESTION";
pub const SCRAPER_ELEMENT_SELECT_QUESTION: &str = "SCRAPER_ELEMENT_SELECT_QUESTION";
pub const SCRAPER_ELEMENT_SELECT_ALL_QUESTION: &str = "SCRAPER_ELEMENT_SELECT_ALL_QUESTION";
